[package]
name = "day02"
version = "0.1.0"
authors = ["Martin Donlon <git-martin@donlons.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent = { path = "../advent" }
thiserror = "1"
